platform :ios, '7.1'

pod 'iRate'
pod 'iVersion'
pod 'Fabric'
pod 'Crashlytics'
pod 'Flurry-iOS-SDK/FlurrySDK'
pod 'iCarousel'
pod 'pop'
pod 'TPKeyboardAvoiding'
pod 'JGProgressHUD'
pod 'UIDevice-Hardware'
